name: legumi
description: "Control inteligente de plagas con IA"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0

  flutter_dotenv: ^5.0.2

  intl: ^0.18.1

  cupertino_icons: ^1.0.8

  flutter_secure_storage: ^9.0.0

  mobile_scanner: ^3.5.6

  qr_flutter: ^4.1.0

  image_picker: ^1.0.7

  shared_preferences: ^2.1.1

  google_fonts: ^6.2.1

  material_symbols_icons: ^4.2815.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/welcome_image.png
    - assets/images/zanahoria.png
    - assets/images/edit.png
    - assets/images/check.png
    - assets/images/cancel.png
    - assets/images/atras.png
    - assets/images/img_hero.png
    - assets/images/hero_result.png
    - assets/images/logo_legumi.png